- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true

- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: "0755"

- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: "{{ rke2_binary_url }}"
    dest: "{{ rke2_install_dir }}/rke2"
    mode: "0755"

- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/rke2"
    mode: "0755"
    state: file

- name: Create directory for rke2 configs & manifests
  ansible.builtin.file:
    path: "/var/lib/rancher/rke2/server/manifests"
    state: directory
    mode: "0755"
  when: inventory_hostname in groups['servers']
