env: "dev"
ansible_user: "ubuntu"
rke2_version: "v1.32.3+rke2r1"
arch: "amd64"
ssl_local_domain: "dev.phuchoang.sbs"
ssl_cloudflare_api_token: 
ssl_email: "xuanphuc.a1gv@gmail.com"
vip: "10.69.1.110"
vip_cidr: "16"
vip_lb_range: "10.69.1.117-10.69.1.119"
vip_ingress_ip: "10.69.1.117"
