ansible_user: ubuntu
rke2_version: "v1.32.3+rke2r1"
arch: amd64
token: dev # for authenticate & add nodes in cluster
env: dev
vip: "10.69.1.110" # for virtual ip of the servers
vip_cidr: "16"
vip_lb_range: "10.69.1.117-10.69.1.119" # load balancer ip
ssl_local_domain: dev.phuchoang.sbs
ssl_cloudflare_api_token:
ssl_email: xuanphuc.a1gv@gmail.com
ssl_ingress_ip: "10.69.1.117" # default traefik ip, must be in the range above
