- name: Create directory for RKE2 config
  ansible.builtin.file:
    path: "/etc/rancher/rke2"
    state: directory
    mode: "0644"

- name: Create systemd service file for RKE2 agent
  ansible.builtin.template:
    src: templates/rke2-agent.service.j2
    dest: /etc/systemd/system/rke2-agent.service
    owner: root
    group: root
    mode: "0644"

# replaces two separate config tasks
- name: Deploy RKE2 Agent or Longhorn Configuration
  ansible.builtin.template:
    src: "{{ 'templates/rke2-longhorn-config.j2' if inventory_hostname in groups['longhorn'] else 'templates/rke2-agent-config.j2' }}"
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"

- name: Ensure RKE2 agents are enabled and running
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: true
    state: restarted
    daemon_reload: true
