- name: Deploy cert-manager-helm-chart.j2
  ansible.builtin.template:
    src: templates/cert-manager-helm-chart.j2
    dest: /var/lib/rancher/rke2/server/manifests/cert-manager-helm-chart.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy cert-manager-issuer.j2
  ansible.builtin.template:
    src: templates/cert-manager-issuer.j2
    dest: /var/lib/rancher/rke2/server/manifests/cert-manager-issuer.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]

- name: Deploy traefik-helm-chart.j2
  ansible.builtin.template:
    src: templates/traefik-helm-chart.j2
    dest: /var/lib/rancher/rke2/server/manifests/traefik-helm-chart.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  when: inventory_hostname == groups['servers'][0]
